# For Silicon ARM-based Macs only -> subject to change -> this env works perfectly as of December '22
name: MultiPersonPose
channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10.0
  - pip==22.3.1  
  - tensorflow-deps
  - ipykernel==6.19.2 # Comment if not using jupyter

  # PyPI packages
  - pip:
    - tensorflow-macos==2.9
    - tensorflow-metal==0.5  
    
